//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CrudOperationInMVC_Bool_Image_Calendar_.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.Web;

    public partial class tblStudent
    {

        public int StudentID { get; set; }

        [DisplayName("Student Name")]
        public string StudentName { get; set; }

        [DisplayName("Student Mail")]
        public string Email { get; set; }

        [DisplayName("Student Status")]
        public Nullable<bool> IsDeleted { get; set; }

        [DisplayName("Student Department")]
        public Nullable<int> DepartmentId { get; set; }

        [DisplayName("Student Photo")]
        public string StudentImage { get; set; }

        [DisplayName("Student Birtday")]
        public Nullable<System.DateTime> Birthday { get; set; }


        public HttpPostedFileBase ImageFile { get; set; }

        public virtual tblDepartment tblDepartment { get; set; }
    }
}
